<h1>NumPy</h1>

In [1]:
import numpy as np

<h2>1D Array

In [19]:
a=np.array([1,2,3,4,5],dtype='int16')
print(a)

[1 2 3 4 5]


<h2>2D Array

In [26]:
b=np.array([[5.2,2.9,8.3,4.1,5.0], [7.0,3.3,9.5,6.0,10.5]], dtype='float32')
print(b)

[[ 5.2  2.9  8.3  4.1  5. ]
 [ 7.   3.3  9.5  6.  10.5]]


<p> Sort</p>

In [264]:
b.sort()   # or   np.sort(b)
b

array([[ 2.9,  4.1,  5. ,  5.2,  8.3],
       [ 3.3,  6. ,  7. ,  9.5, 10.5]], dtype=float32)

In [12]:
# get the no. of dimensions
a.ndim  #---> 1d
b.ndim  #---> 2d

2

In [15]:
# returns the shape (row,col)
b.shape

(2, 5)

In [27]:
# returns the data type (manually able to change the dtype while initializing)
a.dtype  
b.dtype 

dtype('float32')

In [32]:
# returns size of the array
a.itemsize

2

In [33]:
# returns the total size
a.nbytes   # [a.size * a.itemsize]

10

In [34]:
a.size * a.itemsize

10

In [69]:
type(a)

numpy.ndarray

<h3> Accessing/changing specific elements in row/col

In [60]:
c=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [61]:
# accessing a specific element [row, col]
c[1,5]

13

In [62]:
# to get specific row
c[0,:]  # returns 0th row 

array([1, 2, 3, 4, 5, 6, 7])

In [63]:
c[:,2]  # returns the 2nd ele of the col in every row

array([ 3, 10])

In [64]:
# returns the ele of 0th row & col element from index 1 to 5 with the stepsize of 2
c[0,1:5:2]

array([2, 4])

updating the values

In [67]:
c[1,4]=18     # updates
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 18 13 14]]


In [73]:
c[:,2]=[2,9]   # updates the 2nd col with the series of element like 2,9
print(c)

[[ 1  2  2  4  5  6  7]
 [ 8  9  9 11 18 13 14]]


---

<h4>Initializing different types of arrays</h4>

In [78]:
np.zeros((3,2,3,4),dtype='int8')

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]], dtype=int8)

In [ ]:
''' for understaning:

    [0., 0., 0., 0.],       [0., 0., 0., 0.],
    [0., 0., 0., 0.],       [0., 0., 0., 0.],
    [0., 0., 0., 0.],       [0., 0., 0., 0.],

    [0., 0., 0., 0.],        [0., 0., 0., 0.],
    [0., 0., 0., 0.],        [0., 0., 0., 0.],
    [0., 0., 0., 0.],        [0., 0., 0., 0.], 

    [0., 0., 0., 0.],        [0., 0., 0., 0.],
    [0., 0., 0., 0.],        [0., 0., 0., 0.],
    [0., 0., 0., 0.],        [0., 0., 0., 0.],  

structures the arry like this with
    * 3 blocks (1st dim)
    * each 3 blocks contains 2 matices
    * the matrices with the dim of 3*4

'''

In [93]:
np.ones((2,4,2,2), dtype='int32')

array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])

In [ ]:
'''
    * 2 blocks
    * 3 matrices
    * dim of 2*2
'''

In [99]:
# array value with any numbers  --> np.full((row*col), value)
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [236]:
# fills the existing array values with the new value  --> np.full_like(arr_name, value)
np.full_like(c,7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

<h4>Random numbers

In [265]:
import numpy.random

In [266]:
np.random.rand(4,3)  # decimal values

array([[0.22776926, 0.21351439, 0.74619914],
       [0.06991989, 0.38626329, 0.91095865],
       [0.11206525, 0.07375903, 0.94374391],
       [0.92979499, 0.88279827, 0.5409311 ]])

In [115]:
# integer with the values from 5 to 9 forming an matrix of 2*3
np.random.randint(5,9, size=(2,3))  

array([[6, 6, 8],
       [7, 6, 7]])

In [219]:
# matrix with the values of n*n with the diagonal element as 1
np.identity(4, dtype="int")  

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [123]:
# repeate the arr elements
arr=np.array([[4,5,6]])
rep=np.repeat(arr,3,axis=0)  # repeats 3 times on 0th axis(column)
print(rep)

[[4 5 6]
 [4 5 6]
 [4 5 6]]


In [127]:
outp=np.ones((5,5), dtype='int16')
print(outp)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


<h4>Mathematical Operations</h4>

In [168]:
x=np.array([5,6,7,8])
x

array([5, 6, 7, 8])

In [169]:
y=x.copy()
y[2]=20
y

array([ 5,  6, 20,  8])

In [170]:
print("add ",y+2)
print("sub ",y-2)
print("mul ",y*2)
print("div ",y/2)
print("pow ",y**2)
y += 3
print("incr ",y)
y -= 1
print("decr ",y)

add  [ 7  8 22 10]
sub  [ 3  4 18  6]
mul  [10 12 40 16]
div  [ 2.5  3.  10.   4. ]
pow  [ 25  36 400  64]
incr  [ 8  9 23 11]
decr  [ 7  8 22 10]


In [171]:
print(np.sin(y))
print(np.cos(y))
print(np.tan(y))

[ 0.6569866   0.98935825 -0.00885131 -0.54402111]
[ 0.75390225 -0.14550003 -0.99996083 -0.83907153]
[ 0.87144798 -6.79971146  0.00885166  0.64836083]


<h4>Statistics</h4>

In [177]:
stats=np.array([[1,2,3],[4,7,6]])
stats

array([[1, 2, 3],
       [4, 7, 6]])

In [188]:
print(np.min(stats,axis=1))
print(np.max(stats,axis=1))
print(np.sum(stats,axis=0))

[1 4]
[3 7]
[5 9 9]


<h4>Reorganizing Array</h4>

In [201]:
before=np.array([[1,2,3,4],[6,5,7,8]])
print(before)
print()
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [6 5 7 8]]

[[[1 2]
  [3 4]]

 [[6 5]
  [7 8]]]


<h4>Stack

In [249]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

print(np.stack([arr1,arr2],axis=1))   # stacks the matrix a/c to the axis
print(np.vstack([arr1,arr2,arr2,arr1]))  # stacks the element vertically
print(np.hstack([arr1,arr2,arr2,arr1]))  # stacks the element vertically

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]
[1 2 3 4 5 6 7 8 5 6 7 8 1 2 3 4]


In [215]:
v=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[5, 6, 7, 9],[1, 2, 3, 4]])
print(v)
v[1:3,0:2]
v[[0,1,2],[1,2,3]]

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 9]
 [1 2 3 4]]


array([2, 7, 9])

In [217]:
v[2,3]

9

# Matrix design

In [230]:
# 1. create the matrix 
r=np.full((5,5),9)
r

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [231]:
# 2. create matrix with 0's
s=np.zeros((3,3),dtype='int32')
s

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [232]:
# 3. replace the 'r' matrix with 's' by initailzing 
r[1:4,1:4]=s
r

array([[9, 9, 9, 9, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 9, 9, 9, 9]])

In [235]:
# 4. replace the middle element by initailizing
r[2,2]=1
r

array([[9, 9, 9, 9, 9],
       [9, 0, 0, 0, 9],
       [9, 0, 1, 0, 9],
       [9, 0, 0, 0, 9],
       [9, 9, 9, 9, 9]])

-----

<h4>Dimensions</h4>

In [244]:
# returns the dimension of matrix
print(r.ndim)
print(before.ndim)

2
2


<h4>Searching

In [253]:
search=np.where(r==1)  # matrix_name == search_value
search

(array([2], dtype=int64), array([2], dtype=int64))

In [259]:
search=np.where(r%2==1)  # matrix_name with condition == search_value
search

(array([0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 4, 0, 2, 4, 0, 4, 0, 1, 2, 3, 4], dtype=int64))

<h4>Filtering</h4>

In [276]:
z=np.random.randint(10,50, size=(6,5))
z

array([[18, 18, 37, 28, 37],
       [19, 32, 10, 23, 20],
       [24, 43, 25, 41, 16],
       [39, 31, 30, 27, 45],
       [36, 48, 19, 33, 29],
       [34, 44, 38, 26, 15]])

In [284]:
z>35  # returns the bool value in the form of matrix

array([[False, False,  True, False,  True],
       [False, False, False, False, False],
       [False,  True, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True, False, False, False],
       [False,  True,  True, False, False]])

In [285]:
z[z>35]  # returns the elements based on filtering

array([37, 37, 43, 41, 39, 45, 36, 48, 44, 38])